name: Unit Test

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    name: Test
    env:
      NODE_OPTIONS: --max-old-space-size=6144
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: yarn
      - run: yarn
      - run: yarn lint
      - run: yarn build
      - run: yarn test:coverage
